-- Delete existing data
DELETE FROM submissions;

-- Insert sample submissions
INSERT INTO submissions (
    title, 
    creator, 
    description, 
    category, 
    screenshot_url, 
    game_url, 
    ai_code_percentage, 
    engine_used, 
    is_multiplayer, 
    domain_url,
    loading_time_ms,
    username_required
) VALUES 
    (
        'Pixel Dungeon AI',
        '@pixelwizard',
        'A procedurally generated dungeon crawler where every level is uniquely created by AI.',
        'RPG',
        'https://picsum.photos/800/600?random=1',
        'https://pixeldungeon-ai.example.com',
        95,
        'ThreeJS',
        0,
        'pixeldungeon-ai.example.com',
        1200,
        0
    ),
    (
        'Space Racing League',
        '@speedcoder',
        'Multiplayer space racing game with AI-generated tracks and obstacles.',
        'Racing',
        'https://picsum.photos/800/600?random=2',
        'https://spacerace.example.com',
        85,
        'ThreeJS',
        1,
        'spacerace.example.com',
        2000,
        1
    ),
    (
        'AI Chess Master',
        '@chesswizard',
        'Chess with AI-generated piece movements and strategies.',
        'Board Game',
        'https://picsum.photos/800/600?random=3',
        'https://aichess.example.com',
        90,
        'Custom Engine',
        0,
        'aichess.example.com',
        500,
        0
    ),
    (
        'Voxel Warriors',
        '@voxelartist',
        'Team-based battle arena with AI-generated maps and weapons.',
        'Action',
        'https://picsum.photos/800/600?random=4',
        'https://voxelwar.example.com',
        88,
        'ThreeJS',
        1,
        'voxelwar.example.com',
        3000,
        1
    ),
    (
        'Puzzle Prophet',
        '@puzzlemaster',
        'AI creates unique puzzles that adapt to your skill level.',
        'Puzzle',
        'https://picsum.photos/800/600?random=5',
        'https://puzzleprophet.example.com',
        92,
        'Custom Engine',
        0,
        'puzzleprophet.example.com',
        800,
        0
    ),
    (
        'Rhythm Revolution',
        '@beatmaker',
        'AI-generated music creates unique rhythm gameplay every time.',
        'Music',
        'https://picsum.photos/800/600?random=6',
        'https://rhythmrev.example.com',
        87,
        'ThreeJS',
        0,
        'rhythmrev.example.com',
        1500,
        0
    ),
    (
        'Strategy Legends',
        '@strategist',
        'Build and manage your kingdom with AI-powered resource management.',
        'Strategy',
        'https://picsum.photos/800/600?random=7',
        'https://strategylegends.example.com',
        83,
        'Custom Engine',
        1,
        'strategylegends.example.com',
        2500,
        1
    ),
    (
        'Platform Paradise',
        '@platformer',
        'Endless platformer with AI-generated levels and challenges.',
        'Platformer',
        'https://picsum.photos/800/600?random=8',
        'https://platformparadise.example.com',
        89,
        'ThreeJS',
        0,
        'platformparadise.example.com',
        1000,
        0
    ),
    (
        'Cosmic Crafting',
        '@craftmaster',
        'Space exploration and crafting with AI-generated resources and recipes.',
        'Simulation',
        'https://picsum.photos/800/600?random=9',
        'https://cosmiccrafting.example.com',
        86,
        'ThreeJS',
        1,
        'cosmiccrafting.example.com',
        2800,
        1
    ),
    (
        'Horror Maze',
        '@horrordev',
        'Procedurally generated horror maze with AI-created scares.',
        'Horror',
        'https://picsum.photos/800/600?random=10',
        'https://horrormaze.example.com',
        91,
        'ThreeJS',
        0,
        'horrormaze.example.com',
        1800,
        0
    ),
    (
        'Sports League Pro',
        '@sportsmaster',
        'AI-powered sports simulation with dynamic player stats.',
        'Sports',
        'https://picsum.photos/800/600?random=11',
        'https://sportsleague.example.com',
        84,
        'Custom Engine',
        1,
        'sportsleague.example.com',
        1600,
        1
    ),
    (
        'Word Wizard',
        '@wordsmith',
        'AI generates unique word puzzles and challenges.',
        'Word Game',
        'https://picsum.photos/800/600?random=12',
        'https://wordwizard.example.com',
        93,
        'Custom Engine',
        0,
        'wordwizard.example.com',
        400,
        0
    );